name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: ["transport/tcp", "transport/grpc"]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      env:
        GO111MODULE: on
        plugin: "{{ matrix.plugin }}"
      run: |
        cd $plugin
        sed -i "s/replace .*//" go.mod
        go get -v -t -d .
        go test -v .
